language: node_js
node_js:
  - "10"

services:
  - docker

cache:
  directories:
    - node_modules

addons:
  ssh_known_hosts: shrimp.octet.services

matrix:
  fast_finish: true

before_install:
  - npm install -g npm
  - npm install -g codacy-coverage release-it greenkeeper-lockfile ganache-cli@~6.1.8

before_script:
  - greenkeeper-lockfile-update
  # - ganache-cli --port 18545 > ganache-cli.log &
  - git clone https://github.com/DEX-Company/barge.git
  - cd barge
  - git checkout tags/dex-2019-05-24
  - bash -x start_ocean.sh --no-brizo --no-pleuston --local-spree-node 2>&1 > start_ocean.log &
  - cd ..

script:
  - ./scripts/wait_for_migration_and_extract_keeper_artifacts.sh
  - export ETH_PORT=18545; npm run test:cover
  # - npm run report-coverage
  - npm run build
  - npm run doc
  # - ./src/examples/fire_lazers.sh

after_script:
  - greenkeeper-lockfile-upload

notifications:
  email: false

deploy:
  - provider: npm
    email: "devops@oceanprotocol.com"
    api_key: ${NPM_TOKEN}
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: bash scripts/deployDocs.sh shrimp.octet.services docs_deploy dev
    on:
      tags: false
      repo: DEX-Company/starfish-js
      all_branches: true
